[package]
name = "anymone-chat"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "anymone_chat"
path = "src/lib.rs"

[[bin]]
name = "anymone-chat"
path = "src/main.rs"

[dependencies]
anymone-core = { path = "../anymone-core" }
anymone-remote-session = { path = "../anymone-remote-session" }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync", "time", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
